#Snakefile
configfile: "config.yaml"

## Adapt this file for your own needs. /path/ needs to be changed according to your setup.

rule all:
    input:
        expand("/path/{sample}_out_alignment.fas", sample=config["samples"]),
        expand("/path/{sample}_out_consensus.fas", sample=config["samples"])

# Decompress the sra file and split it in 1, 2, or 3 parts. Finally concatenate the parts.
rule fastq_dump_concat:
    input:
        "{sample}.sra"
    output:
        "{sample}_concat.fastq"
    shell:
        "fastq-dump --split-e --readids {input} \n cat {wildcards.sample}*.fastq > {output}"

# (Optional but recommended) Trim adaptors and low quality regions from input.
# Please comment out if not required.

rule TrimGalore:
    input:
        "{sample}_concat.fastq"
    output:
        "{sample}_concat_trimmed.fq"
    shell:
        "perl TrimGalore-0.6.6/trim_galore --no_report_file --dont_gzip --output_dir ./ {input}"

# Convert fastq to fasta
rule fastq2fas:
    input:
        "{sample}_concat_trimmed.fq"
    output:
        "{sample}_trimmed.fas"
    shell:
        "awk '(NR-1)%4 == 0 || (NR-2)%4==0' {input} | tr '@' '>' > {output}"

# Replace spaces in fasta sequence names with underscores
rule f2f_newname:
    input:
        "{sample}_trimmed.fas"
    output:
        "{sample}_trimmed_newname.fas"
    shell:
# Call a program that replaces spaces with underscores in the sequence headers of a given fasta file:
        "fasta2fasta-v1.4 -r ' _' -u {input} {output}"

rule MitoGeneExtractor:
    input:
        DNA = "{sample}_trimmed_newname.fas",
        AA = "protein_consensus.fas"
    output:
        a = "{sample}_out_alignment.fas",
        b = "{sample}_out_consensus.fas",
        c = "{sample}_vulgar.txt",
        d = "{sample}_vulgar.txt.log"
    shell:
        "MitoGeneExtractor -d {input.DNA} -p {input.AA} -o {output.a} -c {output.b} -V {output.c} -n 0 -t 0.5 -r 1 -e /home/usr/bin/exonerate"
